language: python
python:
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y portaudio19-dev libffi-dev libssl-dev
install:
  - pip install nox-automation
script:
  - nox -f google-assistant-grpc/nox.py -s lint
  - nox -f google-assistant-sdk/nox.py -s lint unittest  
